name: Build wheels on emulated Raspberry Pi
on:
  push:

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero2_64_raspios]
        include:
        - target: zero2_64_raspios
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: raspios_lite_arm64:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels in chroot environment
        uses: pguyot/arm-runner-action@v2
        id: build_wheels
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          bind_mount_repository: yes
          optimize_image: no
          import_github_env: yes
          commands: |
            sudo apt-get update -y
            sudo apt-get dist-upgrade -y
            sudo apt-get install -y python3 python3-venv python3-dev python3-pip
            sudo pip3 install --upgrade pip
            sudo pip3 install wheel
            sudo pip3 install scikit_learn==0.22.2.post1
            sudo pip3 wheel scikit_learn==0.22.2.post1
            ls -la
